version: '3'
volumes:
  PGDATA:
networks:
  net:
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: postgres
      POSTGRES_DB: devops
    volumes:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - net
  flyway:
    image: flyway/flyway:8.5.0
    volumes:
      - ./flyway_sql:/flyway/sql
      - ./flyway_conf:/flyway/conf
    networks:
      - net
  liquibase:
    image: liquibase/liquibase:4.7
    volumes:
      - ./liquibase_conf:/liquibase/changelog/
    networks:
      - net